name: Super-Linter

on: [push, pull_request]

jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Super-Linter
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_CSS: true
          FILTER_REGEX_EXCLUDE: >
            ^SpendApp/wwwroot/lib/
            |^SpendApp/obj/
            |^SpendApp/bin/
            |^SpendApp/Views/Shared/_Layout\.cshtml\.css$
            |^SpendApp/wwwroot/css/site\.css$
