name: Super-Linter and Tests

on: [push, pull_request]

jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Super-Linter
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_CSS: true
          FILTER_REGEX_EXCLUDE: >
            ^SpendApp/wwwroot/lib/
            |^SpendApp/obj/
            |^SpendApp/bin/
            |^SpendApp/Views/Shared/_Layout\.cshtml\.css$
            |^SpendApp/obj/Debug/net8\.0/scopedcss/Views/Shared/_Layout\.cshtml\.rz\.scp\.css$
            |^SpendApp/obj/Debug/net8\.0/scopedcss/bundle/SpendApp\.styles\.css$
            |^SpendApp/obj/Debug/net8\.0/scopedcss/projectbundle/SpendApp\.bundle\.scp\.css$
            |^SpendApp/wwwroot/css/site\.css$
            |^SpendApp/wwwroot/lib/bootstrap/.*

  test:
    name: Build and run unit tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore SpendApp.sln

      - name: Build solution
        run: dotnet build SpendApp.sln --no-restore --configuration Release

      - name: Run tests
        run: dotnet test SpendApp.sln --no-build --configuration Release --verbosity normal
